### PR TITLE
update inline strategy

### PR DESCRIPTION
**Pull request by patricklx**
fixes issue #253

### CODE REVIEW

**Comment by evoactivity** [comment]
Thanks for the PR :)

Can you fix up the lint issues and I'll rerun the CI.

**Comment by patricklx** [comment]
Ah, forgot the tests

**Comment by patricklx** [comment]
Sorry, I'm on mobile 😅

**Comment by evoactivity** [comment]
I'm not sure what would have changed to cause the embroider optimized scenario to fail 😐

**Comment by DanMonroe** [comment]
2.4.3 broke our application's svgs as well.  I have confirmed that this PR fixes our issue.  Looking forward to its merge.

**Comment by evoactivity** [comment]
I think this should be safe to merge but I want to do a little digging to see why the test is failing.

**Comment by evoactivity** [comment]
I tried running the tests on the master branch and saw the same issue. Something outside of this repo has changed causing this failure, so I'm just going to merge and cut a new release.

**Pull request merged**
